/* Standalone deterministic game simulation. No network or external code. */
(function(root){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class SabbathGame{
 constructor(){this.reset()}
 reset(){this.mode='intro';this.time=0;this.kills=0;this.cam=0;this.events=[];this.powerUses=0;this.combo=0;this.comboAge=0;this.shake=0;this.hitstop=0;this.player={x:130,z:0,vz:0,hp:100,maxHp:100,nav:0,face:1,attack:0,cooldown:0,evade:0,evadeCd:0,inv:0,moving:false,power:0,transform:0};this.enemies=Array.from({length:10},(_,i)=>({id:i,x:[600,820,1100,1530,1730,1990,2460,2720,3020,3370][i],z:0,hp:i===4||i===9?320:200,maxHp:i===4||i===9?320:200,heavy:i===4||i===9,phase:'idle',timer:0,flash:0,face:-1,dead:false,death:0,spawnX:[600,820,1100,1530,1730,1990,2460,2720,3020,3370][i]}));this.exit=3750;this.markers=new Set()}
 start(){this.mode='playing';this.emit('caption','Дым над слободой. Ни одного голоса.');}
 emit(type,data){this.events.push({type,data})}
 attack(){let p=this.player;if(this.mode!=='playing'||p.cooldown>0||p.evade>0||p.transform>0)return false;this.combo=this.comboAge<1.15?this.combo%3+1:1;this.comboAge=0;p.attack=.34;p.cooldown=this.combo===3?.82:.62;this.emit('swing',this.combo);let hits=0;for(const e of this.enemies){if(e.dead||Math.abs(e.x-p.x)>110||((e.x-p.x)*p.face<-18)||p.z>75)continue;this.damageEnemy(e,([0,18,23,34][this.combo])*(p.power>0?1.5:1));e.x+=p.face*(e.heavy?7:17);hits++}if(hits){const wasReady=p.nav>=100;p.nav=clamp(p.nav+20*hits,0,100);if(!wasReady&&p.nav===100&&p.power===0)this.emit('toast','НАВЬ ПРОСНУЛАСЬ. НАЖМИ C — ПРЕВРАТИТЬСЯ.');this.hitstop=.045;this.shake=3;this.emit('hit',hits)}return true}
 damageEnemy(e,d){if(e.dead)return;e.hp-=d;e.flash=.16;this.emit('sparks',{x:e.x,heavy:e.heavy});if(e.hp<=0){e.dead=true;e.death=1;e.phase='dead';this.kills++;this.player.hp=clamp(this.player.hp+5,0,this.player.maxHp);this.emit('kill',e.x)}else if(e.phase!=='strike'){e.phase='hurt';e.timer=.23}}
 dodge(){let p=this.player;if(this.mode!=='playing'||p.evadeCd>0||p.attack>0||p.transform>0)return false;p.evade=.24;p.evadeCd=.85;p.inv=.30;this.emit('dodge');return true}
 jump(){let p=this.player;if(this.mode==='playing'&&p.z===0&&p.transform===0){p.vz=380;this.emit('jump');return true}return false}
 power(){let p=this.player;if(this.mode!=='playing'||p.nav<100||p.power>0)return false;p.nav=0;p.power=8;p.transform=1.3;p.attack=0;p.evade=0;p.z=0;p.vz=0;p.moving=false;p.maxHp=Math.max(60,p.maxHp-8);p.hp=Math.min(p.hp,p.maxHp);this.powerUses++;this.shake=5;this.emit('power');this.emit('caption','Ещё немного силы. Ещё немного чужого внутри.');return true}
 hurt(d){let p=this.player;if(p.inv>0||p.evade>0||p.transform>0)return;p.hp=Math.max(0,p.hp-d);p.inv=.8;this.shake=5;this.combo=0;this.emit('hurt');if(p.hp===0){this.mode='dead';this.emit('dead')}}
 tick(dt,input={}){if(this.mode!=='playing')return;dt=Math.min(Math.max(dt,0),.05);if(this.hitstop>0){this.hitstop-=dt;return}this.time+=dt;this.comboAge+=dt;let p=this.player;if(p.transform>0){p.transform=Math.max(0,p.transform-dt);if(p.transform===0)this.emit('transformed');return}this.shake=Math.max(0,this.shake-dt*15);for(const k of ['attack','cooldown','evade','evadeCd','inv','power'])p[k]=Math.max(0,p[k]-dt);let axis=(input.right?1:0)-(input.left?1:0);p.moving=!!axis&&p.attack<.10;if(axis&&p.evade<=0)p.face=axis;if(p.evade>0)p.x+=p.face*550*dt;else if(p.moving)p.x+=axis*(p.power>0?140:112)*dt;p.x=clamp(p.x,40,this.exit+60);p.vz-=980*dt;p.z=Math.max(0,p.z+p.vz*dt);if(p.z===0)p.vz=0;if(input.attack)this.attack();for(const e of this.enemies){e.flash=Math.max(0,e.flash-dt);if(e.dead){e.death=Math.max(0,e.death-dt*.7);continue}let dist=Math.abs(e.x-p.x);e.face=e.x>p.x?-1:1;e.timer-=dt;if(e.phase==='hurt'){if(e.timer<=0){e.phase='recover';e.timer=.35}continue}if(e.phase==='windup'&&e.timer<=0){e.phase='strike';e.timer=.18;if(dist<(e.heavy?100:75)&&p.z<48)this.hurt(e.heavy?23:13);this.emit('enemyStrike',{x:e.x,heavy:e.heavy})}else if(e.phase==='strike'&&e.timer<=0){e.phase='recover';e.timer=e.heavy?1.1:.85}else if(e.phase==='recover'&&e.timer<=0)e.phase='idle';if(e.phase==='idle'&&dist<390){if(dist>(e.heavy?75:53)){e.x+=e.face*(e.heavy?37:53)*dt;e.walk=true}else{e.walk=false;e.phase='windup';e.timer=e.heavy?.95:.68;this.emit('warning',e.x)}}else e.walk=false;
 } // Soft barriers keep each group in the scene and prevent skipping the level.
 for(const [gate,ids] of [[1350,[0,1,2]],[2200,[3,4,5]],[3530,[6,7,8,9]]]){if(p.x>gate&&ids.some(i=>!this.enemies[i].dead)){p.x=gate;if(!this.markers.has('gate'+gate)){this.markers.add('gate'+gate);this.emit('toast','ТЕНИ НЕ ВЫПУСКАЮТ. ОЧИСТИ ПУТЬ.')}}}
 this.cam+= (clamp(p.x-355,0,this.exit-830)-this.cam)*Math.min(1,dt*4);
 for(const [x,msg] of [[1380,'У колодца всё ещё лежит ведро. Кто-то собирался вернуться.'],[2270,'Дом рядом. Но тени уже знают его имя.'],[3570,'Десять теней пали. За дверью — тишина.']])if(p.x>x&&!this.markers.has(x)){this.markers.add(x);this.emit('caption',msg)}
 if(this.kills===10&&p.x>=this.exit){this.mode='won';this.emit('won')}
 }
}
root.SabbathGame=SabbathGame;if(typeof module!=='undefined')module.exports={SabbathGame};
})(typeof globalThis!=='undefined'?globalThis:window);
