'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),game=new SabbathGame();
const W=960,H=540,G=440,keys=new Set(),art={},particles=[],ghosts=[];
let last=0,clock=0,captionUntil=0,toastUntil=0,soundOn=false,audio=null,master=null,footstep=0,ready=false;
// All imagery is local; this game makes no network requests except loading its own files.
const assets={hero:'assets/yaromir-atlas.png',demon:'assets/yaromir-demon-atlas.png',enemy:'assets/enemies-atlas.png',bg:'assets/background.png',props:'assets/props-atlas.png'};
Promise.all(Object.entries(assets).map(([key,url])=>new Promise((resolve,reject)=>{let i=new Image();i.onload=()=>{art[key]=i;resolve()};i.onerror=()=>reject(new Error(url));i.src=url}))).then(()=>{ready=true;$('start').disabled=false;$('start').textContent='ВОЙТИ В СЛОБОДУ';}).catch(e=>{$('start').textContent='НЕ УДАЛОСЬ ЗАГРУЗИТЬ ИЗОБРАЖЕНИЯ';$('toast').textContent='Открой index.html из полной папки игры. Не найден: '+e.message;});
const rand=(n)=>{let a=Math.sin(n*127.1+311.7)*43758.5453;return a-Math.floor(a)},clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.ceil(w),Math.ceil(h))}
function glow(x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2)}
function path(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}
function tone(freq,dur,vol,type='sine',slide=1){if(!soundOn||!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq*slide),audio.currentTime+dur);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(vol,audio.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(master);o.start();o.stop(audio.currentTime+dur+.02)}
function noise(dur,vol,cutoff){if(!soundOn||!audio)return;let b=audio.createBuffer(1,audio.sampleRate*dur,audio.sampleRate),v=b.getChannelData(0);for(let i=0;i<v.length;i++)v[i]=(Math.random()*2-1)*(1-i/v.length);let s=audio.createBufferSource(),f=audio.createBiquadFilter(),g=audio.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=cutoff;g.gain.value=vol;s.connect(f).connect(g).connect(master);s.start()}
function initAudio(){if(audio){audio.resume();return}audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.32;master.connect(audio.destination);for(const f of [55,82.41,110.2]){let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type='sine';g.gain.value=.022;o.connect(g).connect(master);o.start()}let size=audio.sampleRate*4,b=audio.createBuffer(1,size,audio.sampleRate),d=b.getChannelData(0);for(let i=0;i<size;i++)d[i]=Math.random()*2-1;let s=audio.createBufferSource(),f=audio.createBiquadFilter(),g=audio.createGain();s.buffer=b;s.loop=true;f.type='lowpass';f.frequency.value=240;g.gain.value=.08;s.connect(f).connect(g).connect(master);s.start()}
function soundToggle(){soundOn=!soundOn;if(soundOn)initAudio();if(master)master.gain.value=soundOn?.32:0;$('sound').textContent='ЗВУК: '+(soundOn?'ВКЛ':'ВЫКЛ')}
$('sound').onclick=soundToggle;
$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else $('stage').requestFullscreen?.()};
function start(){if(!ready)return;clearTouch();game.reset();game.start();particles.length=0;ghosts.length=0;keys.clear();$('intro').hidden=true;$('menu').hidden=true;$('hud').hidden=false;canvas.focus();if(!audio&&!soundOn)soundToggle();}
$('start').onclick=start;$('restart').onclick=start;
function pause(){clearTouch();if(game.mode==='playing'){game.mode='paused';showMenu('ПАУЗА','Тишина между ударами','Путь дождётся тебя.',true)}else if(game.mode==='paused'){game.mode='playing';$('menu').hidden=true;canvas.focus()}keys.clear()}
$('pause').onclick=pause;$('resume').onclick=pause;
function showMenu(label,title,copy,resume=false){$('endlabel').textContent=label;$('endtitle').textContent=title;$('endcopy').textContent=copy;$('resume').hidden=!resume;$('restart').textContent=resume?'НАЧАТЬ ЗАНОВО':'ПРОЙТИ ЕЩЁ РАЗ';$('menu').hidden=false}
function keyName(e){return ({KeyA:'a',KeyD:'d',KeyZ:'j',KeyJ:'j',KeyK:'k',KeyC:'e',KeyE:'e',KeyW:' ',Space:' ',ArrowLeft:'a',ArrowRight:'d',ArrowUp:' ',ShiftLeft:'Shift',ShiftRight:'Shift',Escape:'Escape'})[e.code]||e.key}
function press(key,repeat){if(key==='Escape'&&!repeat){pause();return}if(game.mode!=='playing')return;keys.add(key);if(!repeat){if(key==='j')game.attack();if(key===' ')game.jump();if(key==='Shift'||key==='k')game.dodge();if(key==='e')game.power()}}
window.addEventListener('keydown',e=>{let k=keyName(e);if(['a','d','j','k','e',' ','Shift','Escape'].includes(k)){e.preventDefault();press(k,e.repeat)}});window.addEventListener('keyup',e=>keys.delete(keyName(e)));window.addEventListener('blur',()=>{keys.clear();if(game.mode==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.mode==='playing')pause()});
// Track each finger separately: releasing movement must not interrupt an attack.
const touchPointers=new Map();
function releasePointer(id){const key=touchPointers.get(id);touchPointers.delete(id);if(key&&![...touchPointers.values()].includes(key))keys.delete(key);for(const b of document.querySelectorAll('[data-key]'))b.classList.toggle('held',[...touchPointers.values()].includes(b.dataset.key))}
function clearTouch(){touchPointers.clear();for(const b of document.querySelectorAll('[data-key]'))b.classList.remove('held')}
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button===0){press('j',false);canvas.focus()}});
window.addEventListener('pointerup',e=>{if(e.pointerType==='mouse'&&!touchPointers.has(e.pointerId))keys.delete('j');releasePointer(e.pointerId)});
window.addEventListener('pointercancel',e=>releasePointer(e.pointerId));
window.addEventListener('blur',clearTouch);
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('contextmenu',e=>e.preventDefault());b.addEventListener('pointerdown',e=>{e.preventDefault();if(game.mode!=='playing')return;b.setPointerCapture(e.pointerId);touchPointers.set(e.pointerId,b.dataset.key);b.classList.add('held');press(b.dataset.key,false)});b.addEventListener('lostpointercapture',e=>releasePointer(e.pointerId))}
function prop(index,x,y,width,alpha=1,flip=false){if(!art.props)return;const boxes=[[0,0,510,550],[520,245,510,305],[1045,55,490,490],[0,742,535,270],[540,565,535,437],[1105,600,430,412]],b=boxes[index],h=width*b[3]/b[2];ctx.save();ctx.globalAlpha=alpha;ctx.translate(Math.round(x),Math.round(y));if(flip)ctx.scale(-1,1);ctx.drawImage(art.props,...b,-width/2,-h,width,h);ctx.restore()}
// Each atlas frame is aligned on its feet. Frames have individual anchors to avoid sliding in attacks.
const heroFrames=[[0,0,443,443,216,430],[443,0,443,443,216,430],[886,0,444,443,216,430],[1330,0,444,443,220,430],[0,443,440,444,220,421],[440,443,516,444,204,421],[956,443,438,444,163,421],[1394,443,380,444,160,421]];
const demonFrames=heroFrames.map(f=>f.slice());demonFrames[4]=[0,443,395,444,220,421];demonFrames[5]=[395,443,575,444,249,421];demonFrames[6]=[886,443,529,444,233,421];demonFrames[7]=[1370,443,404,444,184,421];
const demonClips={5:[[0,0],[575,0],[575,180],[498,180],[498,444],[0,444]],6:[[88,0],[529,0],[529,170],[492,170],[492,444],[0,444],[0,190],[88,190]],7:[[0,0],[404,0],[404,444],[44,444],[44,300],[0,300]]};
function hero(frame,x,y,alpha=1){
 if(!art.hero)return;const p=game.player,f=heroFrames[frame];
 const blend=p.transform>0?clamp((1.3-p.transform-.2)/.65,0,1):clamp(p.power/.45,0,1);
 function layer(img,opacity,demonic){if(!img||opacity<=0)return;const f=demonic?demonFrames[frame]:heroFrames[frame],sx=img.width/1774,sy=img.height/887;ctx.save();ctx.globalAlpha=alpha*opacity;ctx.translate(Math.round(x),Math.round(y));ctx.scale(p.face,1);if(demonic&&demonClips[frame]){ctx.beginPath();demonClips[frame].forEach(([u,v],i)=>i?ctx.lineTo((u-f[4])*.30,(v-f[5])*.30):ctx.moveTo((u-f[4])*.30,(v-f[5])*.30));ctx.closePath();ctx.clip()}if(demonic){ctx.shadowColor='#986ad0';ctx.shadowBlur=9}if(p.inv>0&&Math.floor(clock*18)%2===0)ctx.globalAlpha*=.65;ctx.drawImage(img,f[0]*sx,f[1]*sy,f[2]*sx,f[3]*sy,-f[4]*.30,-f[5]*.30,f[2]*.30,f[3]*.30);ctx.restore()}
 layer(art.hero,1-blend,false);layer(art.demon,blend,true);
}
function enemy(e){if(!art.enemy)return;let x=e.x-game.cam,y=G+(e.dead?(1-e.death)*16:0);if(x<-180||x>W+180||e.dead&&e.death<=0)return;let col=e.phase==='windup'?2:e.phase==='strike'?3:e.walk?Math.floor(clock*7)%2:0,row=e.heavy?1:0;let sw=art.enemy.width/4,sh=art.enemy.height/2,scale=e.heavy?.36:.31;ctx.save();ctx.translate(Math.round(x),Math.round(y));ctx.scale(-e.face,1);ctx.globalAlpha=e.dead?e.death:1;let bodyAnchor=[240,230,220,300][col];if(e.flash>0){ctx.filter='brightness(2.8) saturate(.3)'}else if(e.phase==='windup'){ctx.shadowColor='#ee7052';ctx.shadowBlur=12;ctx.filter='brightness(1.35)'}ctx.drawImage(art.enemy,col*sw,row*sh,sw,sh,-bodyAnchor*scale,-(row?415:402)*scale,sw*scale,sh*scale);ctx.restore();if(!e.dead&&Math.abs(e.x-game.player.x)<300){rect(x-23,G-(e.heavy?166:144),46,3,'#080c11');rect(x-23,G-(e.heavy?166:144),46*e.hp/e.maxHp,3,e.heavy?'#ab8196':'#b78b68');if(e.phase==='windup'){ctx.fillStyle='#e9b77b';ctx.font='bold 14px Georgia';ctx.textAlign='center';ctx.fillText('!',x,G-(e.heavy?177:155));}}
}
function renderBackground(cam,t){rect(0,0,W,H,'#202b3c');if(art.bg){let width=1050,height=700,offset=(cam*.11)%width;for(let i=-1;i<2;i++){ctx.save();ctx.translate(i*width-offset,-105);if(i%2){ctx.translate(width,0);ctx.scale(-1,1)}ctx.drawImage(art.bg,0,0,width,height);ctx.restore()}}
 // The river, fog, props, gameplay and foreground all move independently of the distant painting.
 ctx.save();ctx.globalAlpha=.14;for(let i=0;i<65;i++){let x=((rand(i)*1400-cam*.21+t*(2+rand(i+5)*3))%1250+1250)%1250-120;rect(x,355+rand(i+300)*49,8+rand(i+7)*48,1,rand(i+1)>.85?'#d7aa78':'#8199ab')}ctx.restore();
 for(let i=0;i<9;i++){let x=((i*210-cam*.26+t*4)%1700+1700)%1700-200;glow(x,315+Math.sin(i)*20,150,'#9fa9b00b')}
 for(const p of [[1,690,423,230],[2,1550,431,206],[1,2330,423,260],[1,2820,424,220]])prop(p[0],p[1]-cam*.65,p[2],p[3],.80);
 // Broad quiet fighting strip with broken pixel highlights and footprints.
 const ground=ctx.createLinearGradient(0,430,0,540);ground.addColorStop(0,'#1b222390');ground.addColorStop(.4,'#151c22');ground.addColorStop(1,'#090e14');ctx.fillStyle=ground;ctx.fillRect(0,431,W,109);
 for(let i=0;i<440;i++){let x=((rand(i+910)*5000-cam)%5000+5000)%5000;if(x>W)continue;let y=443+rand(i+391)*100;rect(x,y,2+rand(i+321)*15,1+rand(i+999)*2,['#303636','#3d3c36','#4b4640','#1c2630'][i%4])}
 prop(3,120-cam,462,260);prop(5,400-cam,451,180,.9);prop(2,1700-cam,446,185);prop(4,3780-cam,452,315);
 // The warm flowers at home are the surviving human detail.
 if(cam>2500){glow(3750-cam,397,95,'#c9a25018');if(game.kills===10){ctx.fillStyle='#e3c992';ctx.font='12px Georgia';ctx.textAlign='center';ctx.fillText('ДОМ →',Math.min(895,game.exit-cam),265)}}
 for(const gate of [1350,2200,3530]){let locked=gate===1350?game.enemies.slice(0,3).some(e=>!e.dead):gate===2200?game.enemies.slice(3,6).some(e=>!e.dead):game.enemies.slice(6).some(e=>!e.dead);if(locked){let x=gate-cam;if(x>-60&&x<W+60){for(let i=0;i<8;i++)glow(x+Math.sin(t*2+i)*8,G-i*13,30,'#7b689c09');ctx.strokeStyle='#776f8c40';ctx.lineWidth=1;ctx.beginPath();for(let i=0;i<25;i++){let y=G-i*5,x1=x+Math.sin(i*1.8+t*2)*4;i?ctx.lineTo(x1,y):ctx.moveTo(x1,y)}ctx.stroke()}}}
}
function render(){ctx.imageSmoothingEnabled=false;ctx.save();const intro=game.mode==='intro',cam=intro?Math.sin(clock*.035)*60+100:game.cam;let shake=game.mode==='playing'?game.shake:0;ctx.translate((rand(clock)*2-1)*shake,(rand(clock+2)*2-1)*shake*.4);renderBackground(cam,clock);
 if(intro){let prev=game.player.face;game.player.face=-1;hero(0,745,442);game.player.face=prev}else{for(const ghost of ghosts){hero(7,ghost.x-game.cam,G-ghost.z,ghost.life*.3)}for(const e of game.enemies)enemy(e);let p=game.player;ctx.save();ctx.globalAlpha=.38;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(p.x-game.cam,G+3,28,5,0,0,7);ctx.fill();ctx.restore();let frame=p.transform>0?0:p.evade>0?7:p.attack>.25?4:p.attack>.13?5:p.attack>0?6:p.z>0?2:p.moving?1+Math.floor(clock*9)%3:0;hero(frame,p.x-game.cam,G-p.z+(p.moving&&p.z===0?Math.sin(clock*18)*1:Math.sin(clock*2)*.6));
 if(p.attack>0&&p.attack<.25){ctx.save();ctx.translate(p.x-game.cam,G-p.z-64);ctx.scale(p.face,1);ctx.strokeStyle=p.power>0?'#b9a0e8':'#f0cf83';ctx.globalAlpha=Math.sin((.25-p.attack)/.25*Math.PI)*.85;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(23,-9,86,56,.2,-1.1,1.05);ctx.stroke();ctx.lineWidth=1;ctx.strokeStyle='#fff0ce';ctx.stroke();ctx.restore()}
 if(p.transform>0){const t=1.3-p.transform,x=p.x-game.cam;ctx.fillStyle='rgba(15,7,31,'+(.24*Math.sin(t/1.3*Math.PI))+')';ctx.fillRect(0,0,W,H);glow(x,G-72,150,'#a770d94a');ctx.save();ctx.translate(x,G-58);ctx.strokeStyle='#c5a3ee';ctx.globalAlpha=Math.sin(t/1.3*Math.PI)*.8;ctx.lineWidth=2;for(let i=0;i<3;i++){const r=25+t*70+i*17;ctx.beginPath();ctx.ellipse(0,30,r,r*.3,0,0,Math.PI*2);ctx.stroke()}for(let i=0;i<16;i++){let yy=40-((t*160+i*15)%190);rect(Math.sin(i*2.4+t*4)*45,yy,2,7,'#c2a0f6')}ctx.restore()}
 if(p.power>0){ctx.fillStyle='#39275113';ctx.fillRect(0,0,W,H);for(let i=0;i<10;i++)glow(p.x-game.cam+Math.sin(clock*5+i)*30,G-p.z-i*8,20,'#9b83c311')}
 }
 for(const s of particles){rect(s.x-game.cam,s.y,s.size,s.size,s.color)}
 // Foreground framing passes faster than the actor, never covering the central combat area continuously.
 for(const [x,idx,w] of [[-60,0,360],[1130,5,185],[2150,0,350],[3290,5,200],[5000,0,400]])prop(idx,x-cam*1.3,530,w,.8);
 for(let i=0;i<44;i++){let x=((rand(i+55)*1200-clock*(7+rand(i)*10)-cam*.36)%1150+1150)%1150-90,y=(rand(i+35)*560+clock*(3+rand(i+9)*9))%560;rect(x,y,i%7===0?2:1,i%7===0?2:1,i%5===0?'#bc996b85':'#95958a40')}
 ctx.restore();const vignette=ctx.createRadialGradient(W/2,H*.5,H*.18,W/2,H*.5,W*.65);vignette.addColorStop(0,'#050c1300');vignette.addColorStop(1,'#04090fd1');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);rect(0,0,W,9,'#070d13');rect(0,H-9,W,9,'#070d13');
}
function events(){for(const e of game.events.splice(0)){if(e.type==='caption'){$('caption').textContent=e.data;captionUntil=game.time+5.5}else if(e.type==='toast'){$('toast').textContent=matchMedia('(pointer: coarse)').matches?e.data.replace('НАЖМИ C','НАЖМИ «НАВЬ»'):e.data;toastUntil=game.time+5}else if(e.type==='sparks'){for(let i=0;i<14;i++)particles.push({x:e.data.x,y:G-60,vx:(Math.random()-.5)*180,vy:-50-Math.random()*130,life:.25+Math.random()*.5,size:i%3?2:3,color:['#ead9ac','#c38863','#a56153','#867794'][i%4]})}else if(e.type==='swing'){noise(.12,.15,3400);tone(160,.13,.05,'triangle',.4)}else if(e.type==='hit'){noise(.12,.3,1000);tone(70,.14,.2,'sine',.45)}else if(e.type==='kill'){tone(180,.5,.06,'triangle',.5)}else if(e.type==='hurt'){noise(.18,.22,450);tone(90,.2,.13,'sawtooth',.4)}else if(e.type==='dodge'){noise(.2,.08,1800)}else if(e.type==='power'){$('toast').textContent='';toastUntil=0;tone(110,1.5,.15,'sawtooth',2);tone(82,2,.08)}else if(e.type==='enemyStrike'){if(e.data.heavy){noise(.18,.16,200);game.shake=Math.max(game.shake,2)}}else if(e.type==='dead'){showMenu('ПУТЬ ОБОРВАЛСЯ','Река помнит твоё имя','Перед ударом враг вспыхивает. Уйди рывком или подпрыгни.');tone(55,2,.1)}else if(e.type==='won'){const m=Math.floor(game.time/60),s=Math.floor(game.time%60).toString().padStart(2,'0');showMenu('ПЕРЕПРАВА ОЧИЩЕНА','В доме никто не ответил.',`10 теней · ${m}:${s} · Навь призвана ${game.powerUses} раз. Семья не найдена. Путь только начался.`);tone(164.81,2,.06);setTimeout(()=>tone(196,2,.06),300);setTimeout(()=>tone(220,3,.05),700)}}}
function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(game.mode!=='paused')clock+=dt;game.tick(dt,{left:keys.has('a'),right:keys.has('d'),attack:keys.has('j')});events();if(game.mode==='playing'){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=330*dt;if(p.life<=0)particles.splice(i,1)}for(let i=ghosts.length-1;i>=0;i--){ghosts[i].life-=dt*3;if(ghosts[i].life<=0)ghosts.splice(i,1)}if(game.player.evade>0)ghosts.push({x:game.player.x,z:game.player.z,life:1});if(game.player.moving&&game.player.z===0){footstep+=dt;if(footstep>.32){noise(.035,.06,350);footstep=0}}}
 $('health').style.width=game.player.hp+'%';$('hptext').textContent=Math.ceil(game.player.hp);$('power').style.width=(game.player.power>0?game.player.power/8*100:game.player.nav)+'%';$('hud').classList.toggle('demonic',game.player.power>0);$('powertext').textContent=game.player.transform>0?'ПРЕВРАЩЕНИЕ':game.player.power>0?'ДЕМОН · '+game.player.power.toFixed(1)+' С':game.player.nav>=100?'C · НАВЬ / ЦЕНА: 8 МАКС. HP':'НАВЬ · '+Math.floor(game.player.nav)+' / 100';$('kills').innerHTML=game.kills+' <em>/ 10</em>';$('area').textContent=game.player.x<1350?'ПРИСТАНЬ':game.player.x<2200?'СТАРЫЙ КОЛОДЕЦ':game.kills<10?'ДОРОГА ДОМОЙ':'ВОЗВРАЩЕНИЕ';$('caption').style.opacity=game.time<captionUntil?'1':'0';if(game.time>toastUntil)$('toast').textContent='';render();requestAnimationFrame(loop)}
// Read-only state export for reproducible local browser checks.
window.sabbath={game,keys,ready:()=>ready,render};requestAnimationFrame(loop);
